cfg:
  #db:
  #  host: mysql.devxinfei.cn
  #  port: 3306
  #  user: php_user
  #  password: aB557f47A02F83Cd87E4A05679
  #  database: xyf_sms_center
  #
  #redis:
  #  host: localhost
  #  port: 6379
  #  password: ""
  #  database: 0
  #
  #prometheus:
  #  address: :1010
  #
  #jaeger:
  #  address: :6831
  #
  #etcd:
  #  address: 127.0.0.1:2379

  etcdCfgCenter:
    address: 127.0.0.1:2379
  showLogToConsole: true